# Generated by Django 5.2.1 on 2026-05-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='标段名称')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='标段编号')),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档')], default='active', max_length=32, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projects.project', verbose_name='项目')),
            ],
            options={
                'db_table': 'projects_lot',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['project'], name='projects_lo_project_8c26ad_idx')],
            },
        ),
    ]
