# Generated by Django 5.2.1 on 2026-05-21 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_role', models.CharField(choices=[('owner', '负责人'), ('editor', '编辑'), ('reviewer', '评审'), ('viewer', '只读')], max_length=16, verbose_name='项目角色')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_members', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'projects_project_member',
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_57ae0a_idx'), models.Index(fields=['user'], name='projects_pr_user_id_a52982_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_projectmember_project_user')],
            },
        ),
    ]
