# Generated by Django 5.2.1 on 2026-05-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='角色名称')),
                ('code', models.CharField(max_length=64, verbose_name='角色编码')),
                ('permissions', models.JSONField(default=list, verbose_name='权限码列表')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置角色')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认角色')),
            ],
            options={
                'db_table': 'projects_project_role',
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='workflow_status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='not_started', max_length=16, verbose_name='流程状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['workflow_status'], name='projects_lo_workflo_b2314c_idx'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_roles', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='projects.projectrole', verbose_name='项目角色'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['project'], name='projects_pr_project_6ff87d_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_projectrole_project_code'),
        ),
    ]
