# Generated by Django 5.2.1 on 2026-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_migrate_project_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='招标代理机构'),
        ),
        migrations.AddField(
            model_name='lot',
            name='bid_deadline',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='投标截止时间'),
        ),
        migrations.AddField(
            model_name='lot',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='招标联系人'),
        ),
        migrations.AddField(
            model_name='lot',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='招标联系电话'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tenderer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='招标人'),
        ),
    ]
