# Generated by Django 5.2.1 on 2026-05-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_migrate_project_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('scope', models.CharField(choices=[('system', '系统级'), ('project', '项目级')], default='system', max_length=16, verbose_name='作用域')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置模板')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'workflow_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('default_assignee_type', models.CharField(choices=[('role', '角色'), ('user', '用户')], default='role', max_length=16, verbose_name='默认负责人类型')),
                ('default_assignee_role', models.CharField(blank=True, default='', max_length=64, verbose_name='默认负责人角色')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='是否需要审批')),
                ('approver_type', models.CharField(blank=True, choices=[('role', '角色'), ('user', '用户')], default='', max_length=16, verbose_name='审批人类型')),
                ('approver_role', models.CharField(blank=True, default='', max_length=64, verbose_name='审批角色')),
                ('estimated_hours', models.FloatField(blank=True, null=True, verbose_name='预估工时')),
                ('description', models.TextField(blank=True, default='', verbose_name='节点说明')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_node_templates', to=settings.AUTH_USER_MODEL, verbose_name='审批人（用户）')),
                ('default_assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_node_templates', to=settings.AUTH_USER_MODEL, verbose_name='默认负责人（用户）')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_templates', to='workflows.workflowtemplate', verbose_name='所属模板')),
            ],
            options={
                'db_table': 'workflow_node_template',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['scope'], name='workflow_te_scope_14f647_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['project'], name='workflow_te_project_b609bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'system'), ('project__isnull', False), _connector='OR'), name='check_template_scope_project', violation_error_message='项目级模板必须关联项目'),
        ),
        migrations.AddIndex(
            model_name='workflownodetemplate',
            index=models.Index(fields=['workflow_template', 'order'], name='workflow_no_workflo_8d3e84_idx'),
        ),
    ]
