# Generated by Django 5.2.1 on 2026-05-22 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_migrate_project_roles'),
        ('workflows', '0001_initial_workflow_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '已失败'), ('archived', '已归档')], default='not_started', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='projects.lot', verbose_name='关联标段')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='workflows.workflowtemplate', verbose_name='使用的模板')),
            ],
            options={
                'db_table': 'lot_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('order', models.IntegerField(verbose_name='排序序号')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='是否需要审批')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '已失败'), ('skipped', '已跳过')], default='pending', max_length=16, verbose_name='状态')),
                ('assignee_type', models.CharField(choices=[('role', '角色'), ('user', '用户')], default='role', max_length=16, verbose_name='负责人类型')),
                ('assignee_role', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人角色')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='失败时间')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('approval_status', models.CharField(choices=[('not_required', '无需审批'), ('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='not_required', max_length=16, verbose_name='审批状态')),
                ('approver_type', models.CharField(blank=True, choices=[('role', '角色'), ('user', '用户')], default='', max_length=16, verbose_name='审批人类型')),
                ('approver_role', models.CharField(blank=True, default='', max_length=64, verbose_name='审批角色')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_node_instances', to=settings.AUTH_USER_MODEL, verbose_name='实际审批人')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人（用户）')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nodes', to=settings.AUTH_USER_MODEL, verbose_name='负责人（用户）')),
                ('lot_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.lotworkflow', verbose_name='所属流程实例')),
                ('node_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_instances', to='workflows.workflownodetemplate', verbose_name='关联节点模板')),
            ],
            options={
                'db_table': 'workflow_node_instance',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lotworkflow',
            index=models.Index(fields=['lot'], name='lot_workflo_lot_id_b07abf_idx'),
        ),
        migrations.AddIndex(
            model_name='lotworkflow',
            index=models.Index(fields=['status'], name='lot_workflo_status_2e305a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownodeinstance',
            index=models.Index(fields=['lot_workflow', 'order'], name='workflow_no_lot_wor_f903df_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownodeinstance',
            index=models.Index(fields=['status'], name='workflow_no_status_1b4db4_idx'),
        ),
    ]
