# Generated by Django 5.2.1 on 2026-05-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_workflow_instance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('previous_status', models.CharField(max_length=32, verbose_name='变更前状态')),
                ('new_status', models.CharField(max_length=32, verbose_name='变更后状态')),
                ('reason', models.TextField(blank=True, verbose_name='原因/备注')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('lot_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.lotworkflow', verbose_name='工作流实例')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.workflownodeinstance', verbose_name='节点')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '工作流审计日志',
                'verbose_name_plural': '工作流审计日志',
                'db_table': 'workflow_audit_log',
                'indexes': [models.Index(fields=['lot_workflow', 'created_at'], name='workflow_au_lot_wor_fb0c93_idx'), models.Index(fields=['node', 'created_at'], name='workflow_au_node_id_41c39f_idx'), models.Index(fields=['action'], name='workflow_au_action_d5290b_idx')],
            },
        ),
    ]
