# Generated by Django 5.2.1 on 2026-05-21 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(max_length=64, verbose_name='任务类型')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery 任务 ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消'), ('retrying', '重试中')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='当前步骤')),
                ('total_steps', models.PositiveSmallIntegerField(default=1, verbose_name='总步骤数')),
                ('related_object_type', models.CharField(blank=True, max_length=64, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=64, verbose_name='关联对象 ID')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='结果（仅引用/摘要）')),
                ('error_message', models.TextField(blank=True, verbose_name='失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'db_table': 'common_async_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['celery_task_id'], name='common_asyn_celery__3e7e6b_idx'), models.Index(fields=['status'], name='common_asyn_status_b58b12_idx'), models.Index(fields=['task_type'], name='common_asyn_task_ty_90e3fb_idx'), models.Index(fields=['created_by'], name='common_asyn_created_82e401_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='common_asyn_related_c0ce5f_idx')],
            },
        ),
    ]
