# Generated by Django 5.2.1 on 2026-08-06 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', '任务'), ('system', '系统')], default='task', max_length=16, verbose_name='类型')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('message', models.CharField(blank=True, max_length=512, verbose_name='内容')),
                ('task_type', models.CharField(blank=True, max_length=64, verbose_name='任务类型')),
                ('related_object_type', models.CharField(blank=True, max_length=64, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=64, verbose_name='关联对象 ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'db_table': 'notification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_d569bc_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_26141b_idx')],
            },
        ),
    ]
