# Generated by Django 5.2.1 on 2026-08-13 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='首次发布时间')),
                ('offline_at', models.DateTimeField(blank=True, null=True, verbose_name='最近下线时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'announcement',
                'ordering': ['-published_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed', models.BooleanField(default=False, verbose_name='不再提示')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近查看时间')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='不再提示时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次确认时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='notifications.announcement', verbose_name='公告')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公告确认',
                'verbose_name_plural': '公告确认',
                'db_table': 'announcement_ack',
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_announcement_user')],
            },
        ),
    ]
