# Generated by Django 5.2.1 on 2026-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_announcement_announcementack'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='auto_offline_at',
            field=models.DateTimeField(blank=True, help_text='可选：到该时间自动下线，不填则长期发布', null=True, verbose_name='自动下线时间'),
        ),
    ]
