# Generated by Django 5.2.1 on 2026-05-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0003_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('file_category', models.CharField(choices=[('tender_file', '招标文件'), ('attachment', '附件'), ('clarification', '澄清/补遗')], default='tender_file', max_length=32)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('parse_pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('parse_failed', '解析失败'), ('ready', '可用'), ('rejected', '已拒绝'), ('archived', '已归档'), ('upload_expired', '上传过期')], default='uploading', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tender_files', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tender_files', to='projects.lot')),
                ('parse_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_files', to='common.asynctask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_files', to='projects.project')),
            ],
            options={
                'db_table': 'tender_file',
                'indexes': [models.Index(fields=['project'], name='tender_file_project_d836b9_idx'), models.Index(fields=['lot'], name='tender_file_lot_id_1d5976_idx'), models.Index(fields=['status'], name='tender_file_status_402dea_idx'), models.Index(fields=['file_category'], name='tender_file_file_ca_aafa23_idx')],
            },
        ),
    ]
