# Generated by Django 5.2.1 on 2026-05-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderfile',
            options={'verbose_name': '招标文件', 'verbose_name_plural': '招标文件'},
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='file_category',
            field=models.CharField(choices=[('tender_file', '招标文件'), ('attachment', '附件'), ('clarification', '澄清/补遗')], default='tender_file', max_length=32, verbose_name='文件类别'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='file_size',
            field=models.BigIntegerField(verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='object_key',
            field=models.CharField(max_length=512, unique=True, verbose_name='MinIO 对象键'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('parse_pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('parse_failed', '解析失败'), ('ready', '可用'), ('rejected', '已拒绝'), ('archived', '已归档'), ('upload_expired', '上传过期'), ('chunked', '已分块'), ('requirement_extracted', '已抽取条款'), ('indexed', '已索引')], default='uploading', max_length=32, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('parse', '文档解析'), ('chunk', '语义分块'), ('requirement_extract', '条款抽取'), ('embedding', '向量嵌入')], max_length=32, verbose_name='阶段')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('version', models.CharField(max_length=32, verbose_name='处理器版本')),
                ('input_hash', models.CharField(blank=True, max_length=64, verbose_name='输入哈希')),
                ('output_hash', models.CharField(blank=True, max_length=64, verbose_name='输出哈希')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('tender_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_jobs', to='tender.tenderfile', verbose_name='招标文件')),
            ],
            options={
                'verbose_name': '流水线任务',
                'verbose_name_plural': '流水线任务',
                'db_table': 'tender_pipeline_job',
                'indexes': [models.Index(fields=['tender_file', 'stage'], name='tender_pipe_tender__85c883_idx'), models.Index(fields=['status'], name='tender_pipe_status_623999_idx'), models.Index(fields=['stage', 'status'], name='tender_pipe_stage_902ae5_idx')],
            },
        ),
    ]
