# Generated by Django 5.2.1 on 2026-05-25 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_add_pipeline_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃版本')),
                ('markdown_uri', models.CharField(blank=True, max_length=512, verbose_name='Markdown URI')),
                ('raw_result_uri', models.CharField(blank=True, max_length=512, verbose_name='原始解析结果 URI')),
                ('assets_uri', models.CharField(blank=True, max_length=512, verbose_name='资源目录 URI')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='页数')),
                ('parse_engine', models.CharField(blank=True, max_length=50, verbose_name='解析引擎')),
                ('parser_version', models.CharField(blank=True, max_length=32, verbose_name='解析引擎版本')),
                ('parse_quality', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=16, verbose_name='解析质量')),
                ('parse_profile', models.JSONField(blank=True, default=dict, verbose_name='解析配置快照')),
                ('page_map_uri', models.CharField(blank=True, max_length=512, verbose_name='页码映射 URI')),
                ('page_map_summary', models.JSONField(blank=True, default=dict, verbose_name='页码映射摘要')),
                ('section_tree', models.JSONField(blank=True, default=dict, verbose_name='目录树')),
                ('quality_metrics', models.JSONField(blank=True, default=dict, verbose_name='解析质量指标')),
                ('parse_duration', models.FloatField(blank=True, null=True, verbose_name='解析耗时（秒）')),
                ('input_hash', models.CharField(blank=True, max_length=64, verbose_name='输入文件哈希')),
                ('output_hash', models.CharField(blank=True, max_length=64, verbose_name='输出结果哈希')),
                ('tender_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_documents', to='tender.tenderfile', verbose_name='招标文件')),
            ],
            options={
                'verbose_name': '解析文档',
                'verbose_name_plural': '解析文档',
                'db_table': 'tender_parsed_document',
                'indexes': [models.Index(fields=['tender_file', 'is_active'], name='tender_pars_tender__3e61b5_idx'), models.Index(fields=['parser_version'], name='tender_pars_parser__ebb162_idx')],
                'constraints': [models.UniqueConstraint(fields=('tender_file', 'parser_version', 'input_hash'), name='uniq_parsed_document_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tender_file',), name='uniq_active_parsed_document_per_tender_file')],
            },
        ),
    ]
