# Generated by Django 5.2.1 on 2026-05-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_add_parsed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_level', models.CharField(choices=[('section', '章节'), ('clause', '条款'), ('window', '窗口')], max_length=16, verbose_name='分块层级')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分块序号')),
                ('content_hash', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('chunk_type', models.CharField(choices=[('qualification', '资格要求'), ('scoring', '评分办法'), ('tech_req', '技术要求'), ('commercial', '商务条款'), ('legal', '法律条款'), ('submission', '投标递交'), ('clarification', '澄清补遗'), ('schedule', '时间节点'), ('general', '其他说明')], default='general', max_length=32, verbose_name='主类型')),
                ('secondary_types', models.JSONField(blank=True, default=list, verbose_name='次类型数组')),
                ('classification_confidence', models.FloatField(blank=True, null=True, verbose_name='分类置信度')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='匹配的关键词')),
                ('matched_section', models.CharField(blank=True, max_length=255, verbose_name='匹配的章节标题')),
                ('section_title', models.CharField(blank=True, max_length=255, verbose_name='所属章节标题')),
                ('section_path', models.CharField(blank=True, max_length=512, verbose_name='层级路径')),
                ('clause_no', models.CharField(blank=True, max_length=64, verbose_name='条款编号')),
                ('content', models.TextField(verbose_name='文本内容')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Token 数量')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='起始页码')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='结束页码')),
                ('source_offsets', models.JSONField(blank=True, default=dict, verbose_name='原文偏移量')),
                ('is_table', models.BooleanField(default=False, verbose_name='是否表格内容')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='是否强制条款')),
                ('has_deadline', models.BooleanField(default=False, verbose_name='是否含截止时间')),
                ('has_amount', models.BooleanField(default=False, verbose_name='是否含金额')),
                ('has_score', models.BooleanField(default=False, verbose_name='是否含评分')),
                ('has_penalty', models.BooleanField(default=False, verbose_name='是否含惩罚条款')),
                ('has_timeline', models.BooleanField(default=False, verbose_name='是否含时间节点')),
                ('embedding_status', models.CharField(choices=[('pending', '待嵌入'), ('done', '已完成'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=16, verbose_name='嵌入状态')),
                ('embedding_model', models.CharField(blank=True, max_length=64, verbose_name='嵌入模型')),
                ('bm25_text', models.TextField(blank=True, verbose_name='BM25 检索文本')),
                ('parent_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='tender.tenderchunk', verbose_name='父分块')),
                ('parsed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tender.parseddocument', verbose_name='解析文档')),
            ],
            options={
                'verbose_name': '语义分块',
                'verbose_name_plural': '语义分块',
                'db_table': 'tender_chunk',
                'indexes': [models.Index(fields=['parsed_document', 'chunk_index'], name='tender_chun_parsed__71f4b6_idx'), models.Index(fields=['parsed_document', 'chunk_type'], name='tender_chun_parsed__7b2b4e_idx'), models.Index(fields=['parsed_document', 'section_path'], name='tender_chun_parsed__7fb6af_idx'), models.Index(fields=['page_start', 'page_end'], name='tender_chun_page_st_75c31a_idx'), models.Index(fields=['chunk_type'], name='tender_chun_chunk_t_0bbf04_idx'), models.Index(fields=['is_mandatory'], name='tender_chun_is_mand_1e8a27_idx')],
                'constraints': [models.UniqueConstraint(fields=('parsed_document', 'content_hash'), name='uniq_chunk_content_hash')],
            },
        ),
    ]
