# Generated by Django 5.2.1 on 2026-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_add_tender_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfile',
            name='document_text_hash',
            field=models.CharField(blank=True, help_text='SHA256 哈希，用于判断是否需要重新提取', max_length=64, verbose_name='文档全文哈希'),
        ),
        migrations.AddField(
            model_name='tenderfile',
            name='document_text_object_key',
            field=models.CharField(blank=True, help_text='存储 DOCX 解析后的纯文本全文，用于条款抽取', max_length=512, verbose_name='文档全文 MinIO 键'),
        ),
    ]
