# Generated by Django 5.2.1 on 2026-07-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_add_extraction_run_and_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinejob',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
