# Generated by Django 5.2.1 on 2026-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_alter_pipelinejob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderfile',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('parse_pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('parse_failed', '解析失败'), ('ready', '可用'), ('rejected', '已拒绝'), ('archived', '已归档'), ('upload_expired', '上传过期'), ('chunked', '已分块'), ('requirement_extracted', '已抽取条款'), ('requirement_extracted_empty', '未抽到条款'), ('indexed', '已索引')], default='uploading', max_length=32, verbose_name='状态'),
        ),
    ]
