# Generated by Django 5.2.1 on 2026-08-04 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_alter_tenderfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderchunk',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='合并解析时标注 chunk 来源文件；None 表示主文件', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_chunks', to='tender.tenderfile', verbose_name='来源文件'),
        ),
        migrations.AlterField(
            model_name='tenderfile',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('parse_pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('parse_failed', '解析失败'), ('ready', '可用'), ('rejected', '已拒绝'), ('archived', '已归档'), ('upload_expired', '上传过期'), ('chunking', '合并解析中'), ('chunked', '已分块'), ('requirement_extracted', '已抽取条款'), ('requirement_extracted_empty', '未抽到条款'), ('indexed', '已索引')], default='uploading', max_length=32, verbose_name='状态'),
        ),
    ]
