# Generated by Django 5.2.1 on 2026-08-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_tenderchunk_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfile',
            name='main_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tender.tenderfile', verbose_name='所属主文件'),
        ),
    ]
