# Generated by Django 5.2.1 on 2026-05-28
# Initial migration for existing tables

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('minio', 'MinIO'), ('s3', 'AWS S3'), ('oss', '阿里云 OSS')], default='minio', max_length=32)),
                ('endpoint', models.CharField(help_text='存储端点地址', max_length=256)),
                ('public_endpoint', models.CharField(blank=True, help_text='公开访问端点', max_length=256)),
                ('access_key', models.TextField(blank=True, help_text='加密存储的 Access Key')),
                ('secret_key', models.TextField(blank=True, help_text='加密存储的 Secret Key')),
                ('bucket', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('secure', models.BooleanField(default=False, help_text='是否使用 HTTPS')),
                ('proxy_enabled', models.BooleanField(default=False, help_text='是否通过 nginx 代理')),
                ('presign_expire_seconds', models.IntegerField(default=3600, help_text='预签名 URL 过期时间')),
                ('max_upload_size_mb', models.IntegerField(default=100, help_text='最大上传文件大小 MB')),
                ('cors_config', models.JSONField(blank=True, default=dict, help_text='CORS 配置')),
            ],
            options={
                'verbose_name': '存储配置',
                'db_table': 'storage_config',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='default', max_length=64, unique=True)),
                ('retrieval_mode', models.CharField(choices=[('keyword', '关键词检索'), ('semantic', '语义检索'), ('hybrid', '混合检索')], default='hybrid', max_length=32)),
                ('top_k', models.IntegerField(default=10, help_text='检索返回数量')),
                ('max_context_tokens', models.IntegerField(default=4000, help_text='上下文最大 Token 数')),
                ('enable_vector_search', models.BooleanField(default=True)),
                ('enable_rerank', models.BooleanField(default=False)),
                ('embedding_model_config_id', models.IntegerField(blank=True, null=True)),
                ('rerank_model_config_id', models.IntegerField(blank=True, null=True)),
                ('chat_model_config_id', models.IntegerField(blank=True, null=True)),
                ('upload_mode', models.CharField(choices=[('backend_proxy', '后端代理上传（推荐）'), ('presigned_direct', 'MinIO 直传（高级）')], default='backend_proxy', help_text='文件上传模式', max_length=32)),
                ('max_upload_size_mb', models.IntegerField(default=100, help_text='最大上传文件大小 MB')),
                ('enable_audit_log', models.BooleanField(default=True, help_text='是否记录操作审计')),
                ('enable_prompt_log', models.BooleanField(default=False, help_text='是否记录 Prompt 输入输出')),
                ('enable_rag_log', models.BooleanField(default=False, help_text='是否记录 RAG 检索日志')),
                ('mask_secrets', models.BooleanField(default=True, help_text='是否脱敏显示密钥')),
                ('login_fail_lock_count', models.IntegerField(default=5, help_text='登录失败锁定次数')),
            ],
            options={
                'verbose_name': '系统设置',
                'db_table': 'system_setting',
            },
        ),
    ]
