# Generated by Django 5.2.1 on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('provider', models.CharField(choices=[('bailian', '阿里百炼'), ('openai', 'OpenAI')], default='bailian', max_length=32, verbose_name='供应商')),
                ('api_mode', models.CharField(choices=[('openai_compatible', 'OpenAI 兼容接口'), ('dashscope_native', 'DashScope 原生接口')], default='openai_compatible', max_length=32, verbose_name='API 模式')),
                ('model_name', models.CharField(default='text-embedding-v4', max_length=100, verbose_name='模型名称')),
                ('dimension', models.IntegerField(default=1024, verbose_name='向量维度')),
                ('base_url', models.CharField(default='https://dashscope.aliyuncs.com/compatible-mode/v1', max_length=256, verbose_name='Base URL')),
                ('encrypted_api_key', models.TextField(blank=True, verbose_name='加密 API Key')),
                ('api_key_env', models.CharField(blank=True, default='BAILIAN_API_KEY', max_length=64, verbose_name='API Key 环境变量名')),
                ('batch_size', models.IntegerField(default=10, help_text='单次请求最大文本数', verbose_name='批次大小')),
                ('max_tokens_per_text', models.IntegerField(default=8192, verbose_name='单文本最大 Token')),
                ('timeout_seconds', models.IntegerField(default=60, verbose_name='超时秒数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
            ],
            options={
                'verbose_name': 'Embedding 配置',
                'verbose_name_plural': 'Embedding 配置',
                'db_table': 'system_embedding_config',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('is_default',), name='uniq_default_embedding_config')],
            },
        ),
        migrations.CreateModel(
            name='RagSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='rag.defaults', max_length=64, unique=True)),
                ('retrieval_mode', models.CharField(choices=[('postgres_fulltext', 'PostgreSQL 全文检索'), ('vector', '向量检索'), ('hybrid', '混合检索')], default='postgres_fulltext', max_length=32, verbose_name='检索模式')),
                ('top_k', models.IntegerField(default=10, verbose_name='Top K')),
                ('max_context_tokens', models.IntegerField(default=4000, verbose_name='最大上下文 Token')),
                ('enable_vector_search', models.BooleanField(default=False, verbose_name='启用向量检索')),
                ('enable_rerank', models.BooleanField(default=False, verbose_name='启用 Rerank')),
                ('embedding_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_settings', to='system_config.embeddingconfig', verbose_name='Embedding 配置')),
            ],
            options={
                'verbose_name': 'RAG 设置',
                'db_table': 'system_rag_settings',
            },
        ),
    ]
