# Generated by Django 5.2.1 on 2026-05-21 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='动作类型')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='对象 ID')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='附加上下文')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'db_table': 'audit_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor'], name='audit_opera_actor_i_c6156c_idx'), models.Index(fields=['action'], name='audit_opera_action_e481fe_idx'), models.Index(fields=['created_at'], name='audit_opera_created_4a9b26_idx')],
            },
        ),
    ]
