# Generated by Django 5.2.1 on 2026-05-29 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0005_add_tender_requirement'),
        ('tender', '0004_add_tender_chunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_key', models.CharField(help_text='tender_file 内唯一，用于幂等更新', max_length=64, verbose_name='条款唯一键')),
                ('requirement_no', models.CharField(blank=True, help_text='如 ★1、2.1.3、P1-评分项1', max_length=64, verbose_name='条款编号')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序序号')),
                ('requirement_type', models.CharField(choices=[('qualification', '资格要求'), ('tech_req', '技术要求'), ('scoring', '评分项'), ('commercial', '商务条款'), ('legal', '合同法律'), ('submission', '投标递交要求'), ('schedule', '履约周期'), ('material', '材料要求'), ('format', '文件格式要求'), ('clarification', '澄清补遗'), ('other', '其他')], default='other', max_length=32, verbose_name='条款类型')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='条款标题')),
                ('content', models.TextField(help_text='保留原文含义', verbose_name='条款内容')),
                ('summary', models.CharField(blank=True, help_text='AI 生成的概括摘要', max_length=500, verbose_name='内容摘要')),
                ('mandatory_level', models.CharField(choices=[('mandatory', '强制'), ('important', '重要'), ('optional', '可选'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='强制程度')),
                ('risk_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='风险等级')),
                ('response_strategy', models.CharField(choices=[('pending_review', '待确认'), ('comply', '完全响应'), ('partial', '部分响应'), ('deviation', '偏离'), ('explain', '需要说明'), ('provide_material', '提供材料')], default='pending_review', max_length=32, verbose_name='响应策略')),
                ('owner_role', models.CharField(choices=[('bid_manager', '投标经理'), ('sales', '销售'), ('tech', '技术'), ('legal', '法务'), ('finance', '财务'), ('project_manager', '项目经理'), ('other', '其他')], default='bid_manager', max_length=32, verbose_name='责任角色')),
                ('response_needed', models.BooleanField(default=True, verbose_name='需要响应')),
                ('evidence_needed', models.BooleanField(default=False, verbose_name='需要证据材料')),
                ('amount_info', models.JSONField(blank=True, default=dict, help_text='金额、币种等', verbose_name='金额信息')),
                ('deadline_info', models.JSONField(blank=True, default=dict, help_text='截止日期、时间节点等', verbose_name='截止时间信息')),
                ('score_info', models.JSONField(blank=True, default=dict, help_text='分值、评分标准等', verbose_name='评分信息')),
                ('evidence_types', models.JSONField(blank=True, default=list, help_text='需要的证明材料类型列表', verbose_name='证据材料类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('raw_extracted', models.JSONField(blank=True, default=dict, help_text='LLM 原始输出 JSON', verbose_name='原始抽取结果')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('reviewed', '已审核'), ('confirmed', '已确认'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审核状态')),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='来源起始页码')),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='来源结束页码')),
                ('source_section_path', models.CharField(blank=True, max_length=512, verbose_name='来源章节路径')),
                ('source_chunk_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='来源分块序号')),
                ('source_content_hash', models.CharField(blank=True, max_length=64, verbose_name='来源内容哈希')),
                ('extraction_method', models.CharField(choices=[('rule', '规则'), ('llm', 'LLM'), ('hybrid', '混合'), ('manual', '人工')], default='hybrid', max_length=16, verbose_name='抽取方式')),
                ('extractor_version', models.CharField(blank=True, max_length=32, verbose_name='抽取器版本')),
                ('confidence', models.FloatField(blank=True, help_text='0.0 ~ 1.0', null=True, verbose_name='置信度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parsed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='tender.parseddocument', verbose_name='解析文档')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_requirements', to='generation.promptversion', verbose_name='提示词版本')),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='tender.tenderchunk', verbose_name='来源分块')),
                ('source_prompt_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_requirements', to='generation.promptrun', verbose_name='AI 运行记录')),
                ('tender_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tender.tenderfile', verbose_name='招标文件')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requirements', to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '招标条款',
                'verbose_name_plural': '招标条款',
                'db_table': 'requirements_tender_requirement',
                'ordering': ['tender_file', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['tender_file', 'requirement_type'], name='requirement_tender__6dc478_idx'), models.Index(fields=['tender_file', 'mandatory_level'], name='requirement_tender__1e702f_idx'), models.Index(fields=['tender_file', 'risk_level'], name='requirement_tender__691bd1_idx'), models.Index(fields=['tender_file', 'owner_role'], name='requirement_tender__7614fe_idx'), models.Index(fields=['tender_file', 'response_strategy'], name='requirement_tender__cbf5ed_idx'), models.Index(fields=['tender_file', 'is_active'], name='requirement_tender__62ae73_idx'), models.Index(fields=['tender_file', 'review_status'], name='requirement_tender__1504db_idx'), models.Index(fields=['parsed_document'], name='requirement_parsed__1841d7_idx'), models.Index(fields=['source_chunk'], name='requirement_source__6b58d0_idx'), models.Index(fields=['requirement_key'], name='requirement_require_126ab4_idx')],
                'constraints': [models.UniqueConstraint(fields=('tender_file', 'requirement_key'), name='uniq_req_key_per_file')],
            },
        ),
    ]
