# Generated by Django 5.2.1 on 2026-06-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0005_migrate_project_roles'),
        ('requirements', '0001_add_tender_requirement'),
        ('tender', '0005_add_extraction_run_and_document_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('partial_success', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=30, verbose_name='状态')),
                ('extraction_types', models.JSONField(default=list, help_text='["scoring", "mandatory", ...]', verbose_name='抽取类型列表')),
                ('prompt_versions', models.JSONField(default=dict, help_text='{"scoring": {"template_id": 1, "version_id": 2, "version": "v1.0"}, ...}', verbose_name='提示词版本映射')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总抽取数量')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数量')),
                ('failed_types', models.JSONField(default=list, help_text='["scoring", ...]', verbose_name='失败的抽取类型')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('overwrite', models.BooleanField(default=False, help_text='是否覆盖已有条款（删除旧条款后重新抽取）', verbose_name='覆盖已有条款')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('async_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_runs', to='common.asynctask', verbose_name='异步任务')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='projects.project', verbose_name='项目')),
                ('tender_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='tender.tenderfile', verbose_name='招标文件')),
            ],
            options={
                'verbose_name': '条款抽取运行',
                'verbose_name_plural': '条款抽取运行',
                'db_table': 'requirements_extraction_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tender_file'], name='requirement_tender__485f56_idx'), models.Index(fields=['project'], name='requirement_project_780660_idx'), models.Index(fields=['status'], name='requirement_status_5c812e_idx'), models.Index(fields=['created_at'], name='requirement_created_6991bd_idx')],
            },
        ),
    ]
