# Generated by Django 5.2.1 on 2026-06-01 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0006_add_extraction_metadata_fields'),
        ('requirements', '0002_add_extraction_run_and_document_text'),
        ('tender', '0005_add_extraction_run_and_document_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequirement',
            name='extraction_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirements.requirementextractionrun', verbose_name='抽取运行'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='extraction_type',
            field=models.CharField(blank=True, db_index=True, help_text='scoring/mandatory/qualification/commercial/technical/submission', max_length=50, verbose_name='抽取类型'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='LLM 模型'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='prompt_template_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='提示词模板 ID'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='prompt_version_str',
            field=models.CharField(blank=True, max_length=50, verbose_name='提示词版本号'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='raw_llm_item',
            field=models.JSONField(blank=True, help_text='单条款的原始 LLM 输出 JSON', null=True, verbose_name='LLM 原始输出项'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='源页码'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='source_section',
            field=models.CharField(blank=True, max_length=500, verbose_name='源章节'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='source_text',
            field=models.TextField(blank=True, help_text='LLM 抽取时的原文片段', verbose_name='源文本'),
        ),
        migrations.AddIndex(
            model_name='tenderrequirement',
            index=models.Index(fields=['extraction_run'], name='requirement_extract_60209c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderrequirement',
            index=models.Index(fields=['extraction_type'], name='requirement_extract_d4145c_idx'),
        ),
    ]
