# Generated by Django 5.2.1 on 2026-08-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_backfill_score_source_risk_rerun'),
        ('tender', '0007_alter_tenderfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementFilterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extraction_type', models.CharField(db_index=True, max_length=50, verbose_name='抽取类型')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='条款标题')),
                ('matched_keyword', models.CharField(blank=True, max_length=100, verbose_name='命中关键词')),
                ('filter_level', models.CharField(choices=[('hard', '硬过滤'), ('suspected', '疑似标记')], max_length=16, verbose_name='过滤级别')),
                ('filter_reason', models.CharField(blank=True, max_length=255, verbose_name='过滤原因')),
                ('raw_llm_item', models.JSONField(blank=True, null=True, verbose_name='原始 LLM 输出项')),
                ('tender_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_filter_logs', to='tender.tenderfile', verbose_name='招标文件')),
            ],
            options={
                'verbose_name': '条款过滤日志',
                'verbose_name_plural': '条款过滤日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
