# Generated by Django 5.2.1 on 2026-08-04 02:58

from django.db import migrations, models


def backfill_detail_points(apps, schema_editor):
    """从 raw_llm_item 回填 detail_points / classification_reason（与旧 serializer 提取逻辑一致）。"""
    TenderRequirement = apps.get_model("requirements", "TenderRequirement")
    qs = TenderRequirement.objects.exclude(raw_llm_item=None).exclude(raw_llm_item={})
    last_pk = 0
    while True:
        batch = list(qs.filter(pk__gt=last_pk).order_by("pk")[:1000])
        if not batch:
            break
        updates = []
        for req in batch:
            raw = req.raw_llm_item
            if not isinstance(raw, dict):
                continue
            points = raw.get("detail_points")
            reason = raw.get("classification_reason")
            detail_points = points if isinstance(points, list) else []
            classification_reason = reason if isinstance(reason, str) else ""
            if detail_points or classification_reason:
                updates.append(
                    TenderRequirement(
                        pk=req.pk,
                        detail_points=detail_points,
                        classification_reason=classification_reason[:1000],
                    )
                )
        if updates:
            TenderRequirement.objects.bulk_update(
                updates, ["detail_points", "classification_reason"]
            )
        last_pk = batch[-1].pk


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_requirementfilterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequirement',
            name='classification_reason',
            field=models.CharField(blank=True, default='', help_text='3.1 technical 模式：为何归入该类', max_length=1000, verbose_name='归因说明'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='detail_points',
            field=models.JSONField(blank=True, default=list, help_text='groups 模式下的细项要点列表（独立字段，不依赖 raw_llm_item）', verbose_name='细项要点'),
        ),
        migrations.RunPython(backfill_detail_points, migrations.RunPython.noop),
    ]
