# Generated by Django 5.2.1 on 2026-08-05 10:27

from django.conf import settings
from django.db import migrations, models


def activate_latest_successful_run(apps, schema_editor):
    """数据迁移：每个 tender_file 取最新一条 success/partial_success 的 run 置为当前版本。"""
    RequirementExtractionRun = apps.get_model("requirements", "RequirementExtractionRun")
    success_statuses = ["success", "partial_success"]
    activated = 0
    file_ids = set(
        RequirementExtractionRun.objects.values_list("tender_file_id", flat=True)
    )
    for file_id in file_ids:
        latest = (
            RequirementExtractionRun.objects.filter(
                tender_file_id=file_id,
                status__in=success_statuses,
            )
            .order_by("-created_at", "-id")
            .first()
        )
        if latest is not None:
            latest.is_active = True
            latest.save(update_fields=["is_active"])
            activated += 1
    print(f"\nActivated {activated} extraction run(s) as current version.")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_asynctask_force_stopped_asynctask_force_stopped_at'),
        ('projects', '0005_migrate_project_roles'),
        ('requirements', '0007_tenderrequirement_classification_reason_and_more'),
        ('tender', '0008_tenderchunk_source_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementextractionrun',
            name='is_active',
            field=models.BooleanField(default=False, help_text='每个招标文件最多一个当前版本，列表默认只展示当前版本的条款', verbose_name='当前版本'),
        ),
        migrations.AddIndex(
            model_name='requirementextractionrun',
            index=models.Index(fields=['tender_file', 'is_active'], name='requirement_tender__d06d44_idx'),
        ),
        # 数据迁移放在最后：同一事务内先 UPDATE 会导致后续 CREATE INDEX
        # 报 "pending trigger events"；数据迁移自身保证唯一，约束落库安全
        migrations.AddConstraint(
            model_name='requirementextractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tender_file',), name='uniq_active_extraction_run_per_file'),
        ),
        migrations.RunPython(
            activate_latest_successful_run,
            migrations.RunPython.noop,
        ),
    ]
