# Generated by Django 5.2.1 on 2026-08-05 10:50

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_asynctask_force_stopped_asynctask_force_stopped_at'),
        ('projects', '0005_migrate_project_roles'),
        ('requirements', '0008_extraction_run_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequirement',
            name='dedup_status',
            field=models.CharField(choices=[('none', '未去重'), ('kept', '保留'), ('duplicate', '已合并')], db_index=True, default='none', max_length=16, verbose_name='去重状态'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='标段级去重时生成（title + content）', null=True, verbose_name='嵌入向量'),
        ),
        migrations.AddField(
            model_name='tenderrequirement',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='去重后本条被合并到的保留条款', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='requirements.tenderrequirement', verbose_name='合并入条款'),
        ),
        migrations.CreateModel(
            name='RequirementDedupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=30, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, help_text='{"cosine_threshold": 0.92, ...}，降级等运行情况也记录在此', verbose_name='参数快照')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='候选条款总数')),
                ('cluster_count', models.PositiveIntegerField(default=0, help_text='size >= 2 的簇数量', verbose_name='重复簇数量')),
                ('llm_arbitrated_count', models.PositiveIntegerField(default=0, help_text='由 LLM 选出保留条款的簇数量（其余走确定性回退）', verbose_name='LLM 仲裁簇数量')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='已合并条款数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('async_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_dedup_runs', to='common.asynctask', verbose_name='异步任务')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_dedup_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_dedup_runs', to='projects.lot', verbose_name='标段')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_dedup_runs', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '条款去重运行',
                'verbose_name_plural': '条款去重运行',
                'db_table': 'requirements_dedup_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lot'], name='requirement_lot_id_5a2473_idx'), models.Index(fields=['project'], name='requirement_project_cb1e95_idx'), models.Index(fields=['status'], name='requirement_status_745988_idx'), models.Index(fields=['created_at'], name='requirement_created_fb71cc_idx')],
            },
        ),
    ]
