# Generated by Django 5.2.1 on 2026-05-26 08:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('generation', '0001_initial'),
        ('workflows', '0003_workflowauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('kb_type', models.CharField(choices=[('company_profile', '公司介绍'), ('case_library', '项目案例库'), ('qualification', '资质证书库'), ('product', '产品资料库'), ('bid_history', '历史标书库'), ('technical_solution', '技术方案库')], max_length=32, verbose_name='类型')),
                ('visibility', models.CharField(choices=[('system', '系统级'), ('tenant', '企业级'), ('project', '项目级'), ('private', '私有')], default='private', max_length=32, verbose_name='可见范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='分块数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_uri', models.CharField(blank=True, max_length=512, verbose_name='文件URI')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='文件哈希')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME类型')),
                ('parsed_uri', models.CharField(blank=True, max_length=512, verbose_name='解析结果URI')),
                ('raw_result_uri', models.CharField(blank=True, max_length=512, verbose_name='原始解析结果URI')),
                ('parser_version', models.CharField(blank=True, max_length=32, verbose_name='解析器版本')),
                ('chunker_version', models.CharField(blank=True, max_length=32, verbose_name='分块器版本')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('ready', '可用'), ('failed', '失败')], default='uploading', max_length=16, verbose_name='总状态')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('failed', '解析失败')], default='pending', max_length=16, verbose_name='解析状态')),
                ('chunk_status', models.CharField(choices=[('pending', '待分块'), ('chunking', '分块中'), ('chunked', '已分块'), ('failed', '分块失败')], default='pending', max_length=16, verbose_name='分块状态')),
                ('embedding_status', models.CharField(choices=[('skipped', '跳过'), ('pending', '待嵌入'), ('processing', '嵌入中'), ('done', '已嵌入'), ('failed', '嵌入失败')], default='skipped', max_length=16, verbose_name='嵌入状态')),
                ('index_status', models.CharField(choices=[('pending', '待索引'), ('indexing', '索引中'), ('indexed', '已索引'), ('failed', '索引失败')], default='pending', max_length=16, verbose_name='索引状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='分块数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgebase', verbose_name='知识库')),
                ('parse_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='common.asynctask', verbose_name='解析任务')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'knowledge_document',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分块序号')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('section_path', models.CharField(blank=True, max_length=512, verbose_name='章节路径')),
                ('content', models.TextField(verbose_name='内容')),
                ('content_hash', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('chunk_type', models.CharField(choices=[('paragraph', '段落'), ('table', '表格'), ('list', '列表'), ('heading', '标题'), ('code', '代码'), ('general', '通用')], default='general', max_length=32, verbose_name='分块类型')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='起始页')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='结束页')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Token数')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('bm25_text', models.TextField(blank=True, verbose_name='全文检索文本')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('skipped', '跳过'), ('pending', '待嵌入'), ('processing', '嵌入中'), ('done', '已嵌入'), ('failed', '嵌入失败')], default='skipped', max_length=16, verbose_name='嵌入状态')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument', verbose_name='文档')),
            ],
            options={
                'verbose_name': '知识分块',
                'verbose_name_plural': '知识分块',
                'db_table': 'knowledge_chunk',
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField(verbose_name='查询文本')),
                ('knowledge_bases', models.JSONField(default=list, verbose_name='知识库ID列表')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='过滤条件')),
                ('top_k', models.PositiveIntegerField(default=10, verbose_name='Top K')),
                ('retrieval_mode', models.CharField(choices=[('postgres_fulltext', 'PostgreSQL全文检索'), ('keyword', '关键词匹配'), ('vector', '向量检索'), ('hybrid', '混合检索'), ('hybrid_rerank', '混合检索+重排序')], default='postgres_fulltext', max_length=32, verbose_name='检索模式')),
                ('retrieved_chunks', models.JSONField(default=list, verbose_name='检索结果')),
                ('selected_chunks', models.JSONField(blank=True, default=list, verbose_name='最终选中结果')),
                ('latency_ms', models.PositiveIntegerField(verbose_name='耗时毫秒')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('prompt_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='generation.promptrun', verbose_name='提示词运行')),
                ('workflow_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='workflows.workflownodeinstance', verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '检索日志',
                'verbose_name_plural': '检索日志',
                'db_table': 'knowledge_retrieval_log',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['kb_type'], name='knowledge_b_kb_type_bdbab2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['visibility'], name='knowledge_b_visibil_107283_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['is_active'], name='knowledge_b_is_acti_d4b1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['is_deleted'], name='knowledge_b_is_dele_399332_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['knowledge_base'], name='knowledge_d_knowled_8fd15a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['status'], name='knowledge_d_status_79949e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['parse_status'], name='knowledge_d_parse_s_daa78b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['chunk_status'], name='knowledge_d_chunk_s_51fb22_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['is_deleted'], name='knowledge_d_is_dele_7dbd0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__gt', '')), fields=('knowledge_base', 'file_hash'), name='uniq_knowledge_document_file_hash'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='knowledge_c_documen_8e94ec_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['chunk_type'], name='knowledge_c_chunk_t_74eec9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_chunk_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'content_hash'), name='uniq_knowledge_chunk_hash'),
        ),
        migrations.AddIndex(
            model_name='retrievallog',
            index=models.Index(fields=['created_at'], name='knowledge_r_created_bcdd52_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievallog',
            index=models.Index(fields=['prompt_run'], name='knowledge_r_prompt__cae8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievallog',
            index=models.Index(fields=['workflow_node'], name='knowledge_r_workflo_9a0ce8_idx'),
        ),
    ]
