# Generated by Django 5.2 on 2026-06-07
"""添加向量字段支持混合检索。"""

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        # 启用 pgvector 扩展
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            "DROP EXTENSION IF EXISTS vector;",
        ),
        # 添加 embedding 向量字段（1024 维，与百炼 text-embedding-v4 对齐）
        migrations.AddField(
            model_name="knowledgechunk",
            name="embedding",
            field=pgvector.django.VectorField(
                dimensions=1024,
                null=True,
                blank=True,
                verbose_name="嵌入向量",
            ),
        ),
        # 添加向量索引（IVFFlat，适合中等规模数据）
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS knowledge_chunk_embedding_idx
            ON knowledge_chunk
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100);
            """,
            "DROP INDEX IF EXISTS knowledge_chunk_embedding_idx;",
        ),
    ]
