# Generated by Django 5.2.1 on 2026-06-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_add_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='rag_channel',
            field=models.CharField(blank=True, choices=[('company_info', '公司信息'), ('historical_bid', '历史标书'), ('project_case', '项目案例'), ('certificate', '资质证书'), ('personnel', '人员资料'), ('', '按 kb_type 推断')], default='', help_text='覆盖 kb_type 默认通道映射，留空则按 kb_type 推断', max_length=32, verbose_name='RAG通道'),
        ),
        migrations.AddField(
            model_name='retrievallog',
            name='fallback_reason',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='降级原因'),
        ),
        migrations.AddField(
            model_name='retrievallog',
            name='retrieval_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='检索运行ID'),
        ),
        migrations.AddField(
            model_name='retrievallog',
            name='trace_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='trace元数据'),
        ),
    ]
