# Generated by Django 5.2.1 on 2026-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_rag_channel_and_trace_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding_status',
            field=models.CharField(choices=[('skipped', '跳过'), ('pending', '待嵌入'), ('processing', '嵌入中'), ('done', '已嵌入'), ('failed', '嵌入失败')], default='pending', max_length=16, verbose_name='嵌入状态'),
        ),
    ]
