# Generated by Django 5.2.1 on 2026-08-12 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outline', '0022_bidwordtemplate_style_mapping_and_more'),
        ('projects', '0006_lot_agent_lot_bid_deadline_lot_contact_name_and_more'),
        ('tender', '0009_tenderfile_main_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('source_section', models.CharField(blank=True, default='', max_length=255, verbose_name='来源章节')),
                ('status', models.CharField(choices=[('pending', '待识别'), ('analyzing', '识别中'), ('analyzed', '待确认'), ('confirmed', '已确认'), ('generating', '生成中'), ('generated', '已生成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='整体置信度')),
                ('schema_json', models.JSONField(blank=True, default=list, verbose_name='AI识别原始结果')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='识别统计')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_response_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='projects.lot', verbose_name='标段')),
                ('outline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_templates', to='outline.outline', verbose_name='关联大纲(可选)')),
                ('parsed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_templates', to='tender.parseddocument', verbose_name='解析文档')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='projects.project', verbose_name='项目')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='tender.tenderfile', verbose_name='源招标文件')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_response_templates', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '招标响应模板',
                'verbose_name_plural': '招标响应模板',
                'db_table': 'response_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderResponseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('kind', models.CharField(choices=[('main', '响应文件'), ('separate', '单独密封')], default='main', max_length=20, verbose_name='产物类型')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('done', '已完成'), ('failed', '失败')], default='generating', max_length=20, verbose_name='状态')),
                ('object_key', models.CharField(blank=True, default='', max_length=500, verbose_name='MinIO 对象键')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('file_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA256')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_response_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='response_template.tenderresponsetemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '响应文件产物',
                'verbose_name_plural': '响应文件产物',
                'db_table': 'response_template_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_key', models.CharField(help_text='如 附件1/A3-01', max_length=64, verbose_name='块标识')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('block_type', models.CharField(choices=[('FIXED', '固定内容'), ('AUTO_FIELD', '企业自动字段'), ('AI_GENERATE', 'AI生成内容'), ('AI_RESPONSE', '条款应答'), ('DATA_TABLE', '企业数据表'), ('REPEAT_TABLE', '重复行表格'), ('REPEAT_BLOCK', '重复块'), ('MATERIAL_SLOT', '材料插槽'), ('MANUAL', '人工填写'), ('PRICE', '报价')], db_index=True, max_length=20, verbose_name='类型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('is_separate_package', models.BooleanField(default=False, help_text='附件7 报价表等要求单独密封的块', verbose_name='是否单独密封/装订')),
                ('anchor_text', models.CharField(blank=True, default='', help_text='在 docx 中查找的文本片段(段落/表格cell)', max_length=500, verbose_name='定位锚点文本')),
                ('anchor_type', models.CharField(default='text', help_text='text=段落文本 / cell=表格单元格 / row=表格行', max_length=20, verbose_name='锚点类型')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('source_config', models.JSONField(blank=True, default=dict, help_text='AI 生成依据、条款范围、项目需求引用等', verbose_name='来源配置')),
                ('binding_config', models.JSONField(blank=True, default=dict, help_text='AUTO_FIELD: {field: company.name}; MATERIAL_SLOT: {usage_key: ...}', verbose_name='绑定配置')),
                ('ai_result', models.JSONField(blank=True, default=dict, verbose_name='AI识别原始输出')),
                ('confirm_status', models.CharField(choices=[('unconfirmed', '未确认'), ('confirmed', '已确认'), ('adjusted', '已调整')], default='unconfirmed', max_length=20, verbose_name='确认状态')),
                ('fill_status', models.CharField(choices=[('empty', '未填充'), ('filled', '已填充'), ('skipped', '已跳过'), ('needs_review', '待复核')], default='empty', max_length=20, verbose_name='填充状态')),
                ('fill_payload', models.JSONField(blank=True, default=dict, help_text='AI 生成/映射后的填充内容快照', verbose_name='填充内容')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_blocks', to='response_template.tendertemplateblock', verbose_name='父块')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='response_template.tenderresponsetemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '响应模板块',
                'verbose_name_plural': '响应模板块',
                'db_table': 'response_template_block',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='tenderresponsetemplate',
            index=models.Index(fields=['project', 'status'], name='response_te_project_6608e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderresponsetemplate',
            index=models.Index(fields=['source_file'], name='response_te_source__68bc44_idx'),
        ),
        migrations.AddIndex(
            model_name='tendertemplateblock',
            index=models.Index(fields=['template', 'block_type'], name='response_te_templat_d1ebd2_idx'),
        ),
        migrations.AddIndex(
            model_name='tendertemplateblock',
            index=models.Index(fields=['template', 'fill_status'], name='response_te_templat_61d01f_idx'),
        ),
    ]
