# Generated by Django 5.2.1 on 2026-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresponsetemplate',
            name='compiled_file_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='编译模板 MinIO 对象键'),
        ),
    ]
