# Generated by Django 5.2.1 on 2026-05-25 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_migrate_project_roles'),
        ('tender', '0004_add_tender_chunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='供应商键')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('provider_type', models.CharField(help_text='mock / dashscope / openai_compatible', max_length=64, verbose_name='供应商类型')),
                ('base_url', models.CharField(blank=True, max_length=255, verbose_name='Base URL')),
                ('api_key_env', models.CharField(blank=True, default='', max_length=64, verbose_name='API Key 环境变量名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config_defaults', models.JSONField(blank=True, default=dict, verbose_name='默认配置')),
            ],
            options={
                'verbose_name': '模型供应商',
                'verbose_name_plural': '模型供应商',
                'db_table': 'generation_model_provider',
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('embedding', '嵌入模型'), ('rerank', '重排序模型')], default='chat', max_length=16, verbose_name='模型类型')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('temperature', models.FloatField(default=0.2, verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大 Token')),
                ('top_p', models.FloatField(default=0.8, verbose_name='Top P')),
                ('timeout_seconds', models.IntegerField(default=60, verbose_name='超时秒数')),
                ('retry_count', models.IntegerField(default=2, verbose_name='重试次数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='generation.modelprovider', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'db_table': 'generation_model_config',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, verbose_name='模板键')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('scenario', models.CharField(choices=[('outline_generation', '大纲生成'), ('section_writing', '章节撰写'), ('requirement_analysis', '条款分析'), ('requirement_response', '条款响应'), ('scoring_analysis', '评分点分析'), ('deviation_analysis', '偏离分析'), ('evidence_matching', '资料匹配'), ('content_polishing', '内容润色'), ('consistency_check', '一致性检查'), ('tender_qa', '招标问答')], max_length=64, verbose_name='场景')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('scope', models.CharField(choices=[('system', '系统级'), ('tenant', '企业级'), ('project', '项目级'), ('user', '用户级')], default='system', max_length=32, verbose_name='作用域')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'db_table': 'generation_prompt_template',
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('system_prompt', models.TextField(blank=True, verbose_name='系统提示词')),
                ('user_prompt', models.TextField(verbose_name='用户提示词')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema 定义期望输出结构', verbose_name='输出 Schema')),
                ('variable_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema 定义输入变量结构', verbose_name='变量 Schema')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('changelog', models.TextField(blank=True, verbose_name='变更说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='generation.prompttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '提示词版本',
                'verbose_name_plural': '提示词版本',
                'db_table': 'generation_prompt_version',
            },
        ),
        migrations.CreateModel(
            name='PromptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.CharField(max_length=64, verbose_name='场景')),
                ('input_variables', models.JSONField(default=dict, verbose_name='输入变量')),
                ('rendered_system_prompt', models.TextField(blank=True, verbose_name='渲染后系统提示词')),
                ('rendered_user_prompt', models.TextField(verbose_name='渲染后用户提示词')),
                ('output_text', models.TextField(blank=True, verbose_name='输出文本')),
                ('output_json', models.JSONField(blank=True, default=dict, verbose_name='输出 JSON')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示词 Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出 Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 Token')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时毫秒')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='是否包含敏感信息')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.modelconfig', verbose_name='模型配置')),
                ('parsed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.parseddocument', verbose_name='解析文档')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='项目')),
                ('tender_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.tenderfile', verbose_name='招标文件')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='generation.prompttemplate', verbose_name='模板')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.promptversion', verbose_name='版本')),
            ],
            options={
                'verbose_name': '提示词运行',
                'verbose_name_plural': '提示词运行',
                'db_table': 'generation_prompt_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modelconfig',
            index=models.Index(fields=['model_type'], name='generation__model_t_0a3a3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('model_type',), name='uniq_default_model_per_type'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['scenario'], name='generation__scenari_358579_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['scope'], name='generation__scope_02b749_idx'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('key', 'scope', 'project'), name='uniq_prompt_template_scope_project_key'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('key', 'scope'), name='uniq_prompt_template_scope_key'),
        ),
        migrations.AddIndex(
            model_name='promptversion',
            index=models.Index(fields=['template', 'status'], name='generation__templat_97de83_idx'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uniq_prompt_version'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('template',), name='uniq_published_prompt_version_per_template'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['scenario'], name='generation__scenari_c185ee_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['status'], name='generation__status_4d0402_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['prompt_template'], name='generation__prompt__1387f3_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['model_config'], name='generation__model_c_14afd8_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['project'], name='generation__project_7d75f7_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['created_at'], name='generation__created_65bc78_idx'),
        ),
    ]
