# Generated by Django 5.2.1 on 2026-05-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='存储 schema_valid, schema_errors, rag_enabled, retrieval_log_id, retrieval_sources, rag_context_preview 等', verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='promptrun',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('schema_failed', '校验失败')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
