# Generated by Django 4.2 on 2026-06-07
"""添加 Token 用量日志模型。"""

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scenario", models.CharField(help_text="如 section_content_generation, outline_generation", max_length=64, verbose_name="场景")),
                ("prompt_tokens", models.IntegerField(default=0, verbose_name="输入 Token")),
                ("completion_tokens", models.IntegerField(default=0, verbose_name="输出 Token")),
                ("total_tokens", models.IntegerField(default=0, verbose_name="总 Token")),
                ("estimated_cost", models.DecimalField(decimal_places=6, default=0, help_text="美元", max_digits=10, verbose_name="估算成本")),
                ("latency_ms", models.IntegerField(default=0, verbose_name="耗时毫秒")),
                ("status", models.CharField(choices=[("success", "成功"), ("failed", "失败"), ("partial", "部分成功")], default="success", max_length=16, verbose_name="状态")),
                ("prompt_run", models.OneToOneField(on_delete=models.CASCADE, related_name="token_usage", to="generation.promptrun", verbose_name="运行记录")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="token_usages", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="token_usages", to="projects.project", verbose_name="项目")),
                ("prompt_template", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="token_usages", to="generation.prompttemplate", verbose_name="模板")),
                ("model_config", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="token_usages", to="generation.modelconfig", verbose_name="模型配置")),
            ],
            options={
                "verbose_name": "Token 用量日志",
                "verbose_name_plural": "Token 用量日志",
                "db_table": "generation_token_usage_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenusagelog",
            index=models.Index(fields=["user", "created_at"], name="token_usage_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenusagelog",
            index=models.Index(fields=["project", "created_at"], name="token_usage_proj_created_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenusagelog",
            index=models.Index(fields=["scenario"], name="token_usage_scenario_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenusagelog",
            index=models.Index(fields=["created_at"], name="token_usage_created_idx"),
        ),
        migrations.CreateModel(
            name="TokenUsageSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="日期")),
                ("scenario", models.CharField(blank=True, default="", help_text="空表示所有场景汇总", max_length=64, verbose_name="场景")),
                ("total_calls", models.IntegerField(default=0, verbose_name="总调用次数")),
                ("success_calls", models.IntegerField(default=0, verbose_name="成功次数")),
                ("failed_calls", models.IntegerField(default=0, verbose_name="失败次数")),
                ("total_prompt_tokens", models.BigIntegerField(default=0, verbose_name="总输入 Token")),
                ("total_completion_tokens", models.BigIntegerField(default=0, verbose_name="总输出 Token")),
                ("total_tokens", models.BigIntegerField(default=0, verbose_name="总 Token")),
                ("avg_latency_ms", models.IntegerField(default=0, verbose_name="平均延迟 ms")),
                ("total_cost", models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name="总成本")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name="token_summaries", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name="token_summaries", to="projects.project", verbose_name="项目")),
            ],
            options={
                "verbose_name": "Token 用量汇总",
                "verbose_name_plural": "Token 用量汇总",
                "db_table": "generation_token_usage_summary",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenusagesummary",
            index=models.Index(fields=["date"], name="token_summary_date_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenusagesummary",
            index=models.Index(fields=["user", "date"], name="token_summary_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenusagesummary",
            index=models.Index(fields=["project", "date"], name="token_summary_proj_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tokenusagesummary",
            unique_together=[["date", "user", "project", "scenario"]],
        ),
    ]