# Generated by Django 5.2.1 on 2026-05-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_add_prompt_run_metadata_and_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='encrypted_api_key',
            field=models.TextField(blank=True, help_text='加密存储的 API Key', verbose_name='加密 API Key'),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='provider_type',
            field=models.CharField(help_text='mock / dashscope / deepseek / openai_compatible', max_length=64, verbose_name='供应商类型'),
        ),
    ]
