# Generated by Django 5.2.1 on 2026-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_add_embedding_config_and_provider_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='enable_thinking',
            field=models.BooleanField(default=False, help_text='DeepSeek V4 专用：启用思考模式（reasoning）', verbose_name='启用思考模式'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='reasoning_effort',
            field=models.CharField(blank=True, default='', help_text='DeepSeek V4 专用：low/medium/high', max_length=16, verbose_name='推理强度'),
        ),
    ]
