# Generated by Django 5.2.1 on 2026-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_add_tender_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='scenario',
            field=models.CharField(choices=[('outline_generation', '大纲生成'), ('section_writing', '章节撰写'), ('requirement_analysis', '条款分析'), ('requirement_response', '条款响应'), ('requirement_extraction', '条款抽取'), ('requirement_extraction_scoring', '评分项抽取'), ('requirement_extraction_mandatory', '强制条款抽取'), ('requirement_extraction_qualification', '资格要求抽取'), ('requirement_extraction_commercial', '商务条款抽取'), ('requirement_extraction_technical', '技术要求抽取'), ('requirement_extraction_submission', '递交要求抽取'), ('scoring_analysis', '评分点分析'), ('deviation_analysis', '偏离分析'), ('evidence_matching', '资料匹配'), ('content_polishing', '内容润色'), ('consistency_check', '一致性检查'), ('tender_qa', '招标问答')], max_length=64, verbose_name='场景'),
        ),
    ]
