# Generated by Django 5.2.1 on 2026-06-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_token_usage'),
        ('generation', '0006_add_extraction_metadata_fields'),
    ]

    operations = [
    ]
