# Generated by Django 5.2.1 on 2026-05-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='权限码')),
                ('name', models.CharField(max_length=128, verbose_name='显示名')),
                ('module', models.CharField(max_length=64, verbose_name='所属模块')),
                ('scope', models.CharField(choices=[('global', '全局'), ('project', '项目')], max_length=16, verbose_name='作用域')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'accounts_permission',
                'ordering': ['module', 'code'],
            },
        ),
    ]
