# Generated by Django 5.2.1 on 2026-05-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('password', '账号密码'), ('dingtalk', '钉钉'), ('ldap', 'LDAP'), ('wecom', '企业微信'), ('oauth2', 'OAuth2')], max_length=32, verbose_name='认证源')),
                ('external_id', models.CharField(max_length=255, verbose_name='外部身份标识')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auth_identity',
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_authidentity_provider_external')],
            },
        ),
    ]
