# Generated by Django 4.2 on 2026-06-07
"""添加企业资料中心权限码。"""

from django.db import migrations


def add_enterprise_permissions(apps, schema_editor):
    """同步企业资料中心权限到数据库。"""
    Permission = apps.get_model("accounts", "Permission")
    from apps.accounts.permissions_registry import apply_registry
    apply_registry(Permission)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_seed_roles"),
    ]

    operations = [
        migrations.RunPython(add_enterprise_permissions),
    ]
