# Generated by Django 4.2 on 2026-06-07
"""企业资料中心初始迁移。"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("outline", "0006_add_object_key_to_bid_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 公司主体表
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="公司名称"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="公司简称",
                    ),
                ),
                (
                    "unified_social_credit_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        unique=True,
                        verbose_name="统一社会信用代码",
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="法定代表人",
                    ),
                ),
                (
                    "registered_capital",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="注册资本",
                    ),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="成立日期",
                    ),
                ),
                (
                    "registered_address",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="注册地址",
                    ),
                ),
                (
                    "business_scope",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="经营范围",
                    ),
                ),
                (
                    "company_intro",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="公司简介",
                    ),
                ),
                (
                    "official_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "official_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="官网",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="联系人",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="开户银行",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="银行账号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("active", "启用"), ("archived", "归档")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本号"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="系统只能有一个默认公司",
                        verbose_name="默认公司",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司主体",
                "verbose_name_plural": "公司主体",
                "db_table": "enterprise_company_profile",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        # 企业材料表
        migrations.CreateModel(
            name="CompanyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("business_license", "营业执照"),
                            ("legal_id_front", "法人身份证正面"),
                            ("legal_id_back", "法人身份证背面"),
                            ("authorization_letter", "授权委托书"),
                            ("agent_id_front", "委托代理人身份证正面"),
                            ("agent_id_back", "委托代理人身份证背面"),
                            ("certificate", "资质证书"),
                            ("iso_certificate", "体系认证证书"),
                            ("case_contract", "案例合同"),
                            ("acceptance_report", "验收报告"),
                            ("social_security", "社保证明"),
                            ("bank_account", "开户许可证"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="材料类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="材料名称"),
                ),
                (
                    "object_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MinIO 中的对象路径",
                        max_length=500,
                        verbose_name="MinIO 对象键",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="文件大小（字节）",
                        verbose_name="文件大小",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MIME 类型",
                        max_length=100,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="有效期开始",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="有效期结束",
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="发证机构",
                    ),
                ),
                (
                    "certificate_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="证书编号",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="OCR解析文本",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="标签",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="身份证、授权书等敏感材料",
                        verbose_name="是否敏感材料",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("expired", "已过期"),
                            ("archived", "归档"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="enterprise.companyprofile",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业材料",
                "verbose_name_plural": "企业材料",
                "db_table": "enterprise_company_material",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="companymaterial",
            index=models.Index(fields=["company", "material_type"], name="company_material_type_idx"),
        ),
        migrations.AddIndex(
            model_name="companymaterial",
            index=models.Index(fields=["is_sensitive"], name="material_sensitive_idx"),
        ),
        # 标书材料包表
        migrations.CreateModel(
            name="BidMaterialPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="材料包名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("confirmed", "已确认"),
                            ("locked", "已锁定"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "company_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="锁定时的公司信息快照",
                        verbose_name="公司信息快照",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="锁定时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_packages",
                        to="enterprise.companyprofile",
                        verbose_name="公司主体",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_packages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "outline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_package",
                        to="outline.outline",
                        verbose_name="所属大纲",
                    ),
                ),
            ],
            options={
                "verbose_name": "标书材料包",
                "verbose_name_plural": "标书材料包",
                "db_table": "enterprise_bid_material_package",
            },
        ),
        # 材料包明细表
        migrations.CreateModel(
            name="BidMaterialPackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_key",
                    models.CharField(
                        db_index=True,
                        help_text="如 business_license, legal_id_front, qualification_iso9001",
                        max_length=100,
                        verbose_name="用途标识",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="显示顺序",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        verbose_name="是否必需",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="备注",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="enterprise.companymaterial",
                        verbose_name="材料",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="enterprise.bidmaterialpackage",
                        verbose_name="所属材料包",
                    ),
                ),
            ],
            options={
                "verbose_name": "材料包明细",
                "verbose_name_plural": "材料包明细",
                "db_table": "enterprise_bid_material_package_item",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="bidmaterialpackageitem",
            index=models.Index(fields=["package", "usage_key"], name="package_usage_key_idx"),
        ),
        migrations.AddConstraint(
            model_name="bidmaterialpackageitem",
            constraint=models.UniqueConstraint(
                fields=("package", "usage_key"),
                name="uniq_package_usage_key",
            ),
        ),
    ]
