# Generated by Django 4.2 on 2026-06-07
"""添加材料表组合索引优化过期查询。"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="companymaterial",
            index=models.Index(fields=["status", "valid_to"], name="material_status_valid_idx"),
        ),
    ]
