# Generated by Django 5.2.1 on 2026-08-04 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_add_material_status_valid_index'),
        ('outline', '0017_rename_idx_global_fact_outline_outline_glo_outline_e94224_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bidmaterialpackageitem',
            new_name='enterprise__package_7f0d5c_idx',
            old_name='package_usage_key_idx',
        ),
        migrations.RenameIndex(
            model_name='companymaterial',
            new_name='enterprise__company_2c8320_idx',
            old_name='company_material_type_idx',
        ),
        migrations.RenameIndex(
            model_name='companymaterial',
            new_name='enterprise__is_sens_48e297_idx',
            old_name='material_sensitive_idx',
        ),
        migrations.AlterField(
            model_name='companymaterial',
            name='material_type',
            field=models.CharField(choices=[('business_license', '营业执照'), ('legal_id_front', '法人身份证正面'), ('legal_id_back', '法人身份证背面'), ('authorization_letter', '授权委托书'), ('agent_id_front', '委托代理人身份证正面'), ('agent_id_back', '委托代理人身份证背面'), ('qualification', '资格证明'), ('certificate', '资质证书'), ('iso_certificate', '体系认证证书'), ('case_contract', '案例合同'), ('case', '业绩案例'), ('acceptance_report', '验收报告'), ('social_security', '社保证明'), ('bank_account', '开户许可证'), ('other', '其他')], db_index=True, max_length=50, verbose_name='材料类型'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='bidmaterialpackage',
            index=models.Index(fields=['outline'], name='enterprise__outline_8bb55d_idx'),
        ),
        migrations.AddIndex(
            model_name='bidmaterialpackage',
            index=models.Index(fields=['status'], name='enterprise__status_08bf10_idx'),
        ),
        migrations.AddIndex(
            model_name='companymaterial',
            index=models.Index(fields=['status'], name='enterprise__status_24dfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='companymaterial',
            index=models.Index(fields=['valid_to'], name='enterprise__valid_t_8d0cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['status'], name='enterprise__status_a1e0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['is_default'], name='enterprise__is_defa_bfa3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['unified_social_credit_code'], name='enterprise__unified_5a1874_idx'),
        ),
    ]
