# Generated by Django 5.2.1 on 2026-08-12 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_rename_package_usage_key_idx_enterprise__package_7f0d5c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, verbose_name='甲方名称')),
                ('client_contact', models.CharField(blank=True, default='', help_text='姓名、职务、联系电话', max_length=255, verbose_name='甲方证明人')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='实施金额(万元)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='项目开始年月')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='项目结束年月')),
                ('scope', models.TextField(blank=True, default='', verbose_name='项目范围概述')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('source', models.CharField(choices=[('manual', '手动录入'), ('import', '系统导入')], default='manual', max_length=20, verbose_name='来源')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='enterprise.companyprofile', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '企业项目案例',
                'verbose_name_plural': '企业项目案例',
                'db_table': 'enterprise_company_case',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'project_name'], name='enterprise__company_3bfcee_idx'), models.Index(fields=['company', 'client_name'], name='enterprise__company_69acb2_idx')],
            },
        ),
    ]
