# Generated by Django 5.2.1 on 2026-08-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_companycase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('role', models.CharField(blank=True, default='', max_length=128, verbose_name='角色/岗位')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='职称')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='工作年限')),
                ('certificates', models.TextField(blank=True, default='', help_text='如 CISP、CISSP、PMP 等, 逗号分隔', verbose_name='专业证书')),
                ('projects', models.TextField(blank=True, default='', help_text='参与过的项目简要描述', verbose_name='项目经历')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise.companyprofile', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_members', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_materials', to='enterprise.companymaterial', verbose_name='社保证明材料')),
            ],
            options={
                'verbose_name': '项目人员',
                'verbose_name_plural': '项目人员',
                'db_table': 'enterprise_project_member',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'name'], name='enterprise__company_94fb31_idx'), models.Index(fields=['company', 'role'], name='enterprise__company_0e8635_idx')],
            },
        ),
    ]
