/* 由 scripts/export_template_variables.py 生成，勿手改 */
window.BID_TEMPLATE_VARIABLES = {
  "groups": [
    {
      "category": "project",
      "category_name": "项目信息",
      "variables": [
        {
          "key": "project.name",
          "name": "项目名称",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Project.name",
          "required": true,
          "example": "某某银行核心系统建设项目",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.name"
        },
        {
          "key": "project.code",
          "name": "项目编号",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Project.code",
          "required": false,
          "example": "ZB-2026-001",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.code"
        },
        {
          "key": "project.package_name",
          "name": "标段名称",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.name",
          "required": false,
          "example": "标段一",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.package_name"
        },
        {
          "key": "project.package_no",
          "name": "标段编号",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.code",
          "required": false,
          "example": "01",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.package_no"
        },
        {
          "key": "project.tenderer",
          "name": "招标人",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.tenderer",
          "required": false,
          "example": "某某银行股份有限公司",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.tenderer"
        },
        {
          "key": "project.agent",
          "name": "招标代理机构",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.agent",
          "required": false,
          "example": "某某招标代理有限公司",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.agent"
        },
        {
          "key": "project.bid_deadline",
          "name": "投标截止时间",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.bid_deadline",
          "required": false,
          "example": "2026-09-01 09:30",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.bid_deadline"
        },
        {
          "key": "project.contact_name",
          "name": "联系人",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.contact_name",
          "required": false,
          "example": "张三",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.contact_name"
        },
        {
          "key": "project.contact_phone",
          "name": "联系电话",
          "category": "project",
          "category_name": "项目信息",
          "data_type": "string",
          "source": "Lot.contact_phone",
          "required": false,
          "example": "0571-88888888",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:project.contact_phone"
        }
      ]
    },
    {
      "category": "company",
      "category_name": "企业信息",
      "variables": [
        {
          "key": "company.name",
          "name": "企业名称",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.name",
          "required": true,
          "example": "某某科技有限公司",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.name"
        },
        {
          "key": "company.credit_code",
          "name": "统一社会信用代码",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.unified_social_credit_code",
          "required": false,
          "example": "91330100MA0000000X",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.credit_code"
        },
        {
          "key": "company.legal_representative",
          "name": "法定代表人",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.legal_representative",
          "required": false,
          "example": "李四",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.legal_representative"
        },
        {
          "key": "company.registered_capital",
          "name": "注册资本",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.registered_capital",
          "required": false,
          "example": "5000万元",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.registered_capital"
        },
        {
          "key": "company.established_date",
          "name": "成立日期",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.established_date",
          "required": false,
          "example": "2010-01-01",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.established_date"
        },
        {
          "key": "company.address",
          "name": "注册地址",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.registered_address",
          "required": false,
          "example": "杭州市西湖区……",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.address"
        },
        {
          "key": "company.phone",
          "name": "联系电话",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.official_phone",
          "required": false,
          "example": "0571-66666666",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.phone"
        },
        {
          "key": "company.email",
          "name": "邮箱",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.official_email",
          "required": false,
          "example": "bid@example.com",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.email"
        },
        {
          "key": "company.bank_name",
          "name": "开户银行",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.bank_name",
          "required": false,
          "example": "中国银行某某支行",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.bank_name"
        },
        {
          "key": "company.bank_account",
          "name": "银行账号",
          "category": "company",
          "category_name": "企业信息",
          "data_type": "string",
          "source": "CompanyProfile.bank_account",
          "required": false,
          "example": "377600000000000",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:company.bank_account"
        }
      ]
    },
    {
      "category": "system",
      "category_name": "系统变量",
      "variables": [
        {
          "key": "system.export_date",
          "name": "生成日期",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "导出时的日期",
          "required": false,
          "example": "2026-08-11",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.export_date"
        },
        {
          "key": "system.export_datetime",
          "name": "生成时间",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "导出时的日期时间",
          "required": false,
          "example": "2026-08-11 14:30:00",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.export_datetime"
        },
        {
          "key": "system.year",
          "name": "当前年份",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "",
          "required": false,
          "example": "2026",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.year"
        },
        {
          "key": "system.month",
          "name": "当前月份",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "",
          "required": false,
          "example": "08",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.month"
        },
        {
          "key": "system.day",
          "name": "当前日",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "",
          "required": false,
          "example": "11",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.day"
        },
        {
          "key": "system.user_name",
          "name": "操作人",
          "category": "system",
          "category_name": "系统变量",
          "data_type": "string",
          "source": "导出操作人",
          "required": false,
          "example": "王五",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:system.user_name"
        }
      ]
    },
    {
      "category": "document",
      "category_name": "文档信息",
      "variables": [
        {
          "key": "document.title",
          "name": "文档标题",
          "category": "document",
          "category_name": "文档信息",
          "data_type": "string",
          "source": "BidDocument.title",
          "required": false,
          "example": "投标文件",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:document.title"
        },
        {
          "key": "document.version",
          "name": "文档版本",
          "category": "document",
          "category_name": "文档信息",
          "data_type": "string",
          "source": "BidDocument.version",
          "required": false,
          "example": "3",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:document.version"
        },
        {
          "key": "document.generated_at",
          "name": "生成时间",
          "category": "document",
          "category_name": "文档信息",
          "data_type": "string",
          "source": "BidDocument.created_at",
          "required": false,
          "example": "2026-08-11 14:30",
          "description": "",
          "control_type": "var",
          "control_tag": "bid.var:document.generated_at"
        }
      ]
    },
    {
      "category": "special",
      "category_name": "特殊内容",
      "variables": [
        {
          "key": "body",
          "name": "标书正文",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "Outline 全部章节内容",
          "required": true,
          "example": "",
          "description": "AI 生成的标书正文插入位置；每个模板至少需要一个正文类插槽",
          "control_type": "slot",
          "control_tag": "bid.slot:body"
        },
        {
          "key": "role.qualification",
          "name": "资格册（资格证明材料）",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=qualification 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 qualification 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.qualification"
        },
        {
          "key": "role.technical_solution",
          "name": "技术册（技术方案）",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=technical_solution 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 technical_solution 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.technical_solution"
        },
        {
          "key": "role.business_response",
          "name": "商务册（商务响应）",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=business_response 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 business_response 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.business_response"
        },
        {
          "key": "role.service_plan",
          "name": "服务方案册",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=service_plan 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 service_plan 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.service_plan"
        },
        {
          "key": "role.team_intro",
          "name": "团队介绍册",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=team_intro 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 team_intro 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.team_intro"
        },
        {
          "key": "role.attachment",
          "name": "附件册",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "slot",
          "source": "section_role=attachment 的章节",
          "required": false,
          "example": "",
          "description": "只渲染责任矩阵角色为 attachment 的章节（含其子章节）",
          "control_type": "slot",
          "control_tag": "bid.slot:role.attachment"
        },
        {
          "key": "company.logo",
          "name": "企业 Logo",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "image",
          "source": "CompanyProfile.logo",
          "required": false,
          "example": "",
          "description": "企业 Logo 图片；页眉中使用需在占位图上设置替换标记",
          "control_type": "image",
          "control_tag": "bid.image:company.logo"
        },
        {
          "key": "material",
          "name": "企业材料",
          "category": "special",
          "category_name": "特殊内容",
          "data_type": "image",
          "source": "CompanyMaterial（按用途标识）",
          "required": false,
          "example": "",
          "description": "营业执照、资质证书等材料，插入时需指定材料用途标识",
          "control_type": "material",
          "control_tag": "bid.material:material"
        }
      ]
    }
  ]
};
