# Generated by Django 5.2.1 on 2026-06-03 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('generation', '0006_add_extraction_metadata_fields'),
        ('projects', '0005_migrate_project_roles'),
        ('tender', '0005_add_extraction_run_and_document_text'),
        ('workflows', '0003_workflowauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetOutlineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('category', models.CharField(blank=True, help_text='如：工程类、服务类、货物类（可选）', max_length=50, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '预设大纲模板',
                'verbose_name_plural': '预设大纲模板',
                'db_table': 'outline_preset_template',
            },
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='大纲名称')),
                ('source', models.CharField(choices=[('preset', '系统预设'), ('ai', 'AI解析')], max_length=20, verbose_name='来源')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_current', models.BooleanField(default=True, help_text='每个标段只能有一个当前大纲', verbose_name='是否当前大纲')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='projects.lot', verbose_name='标段')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='projects.project', verbose_name='项目')),
                ('source_tender_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.tenderfile', verbose_name='源招标文件')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflowtemplate', verbose_name='工作流实例')),
            ],
            options={
                'verbose_name': '投标大纲',
                'verbose_name_plural': '投标大纲',
                'db_table': 'outline',
            },
        ),
        migrations.CreateModel(
            name='PresetSectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='章节标题')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='outline.presetsectiontemplate', verbose_name='父章节模板')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='outline.presetoutlinetemplate', verbose_name='大纲模板')),
            ],
            options={
                'verbose_name': '预设章节模板',
                'verbose_name_plural': '预设章节模板',
                'db_table': 'outline_preset_section_template',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='章节标题')),
                ('level', models.PositiveIntegerField(default=1, help_text='根据 parent 自动计算，顶级章节为 1', verbose_name='层级')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='同一 parent 下的排序序号', verbose_name='排序')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('reviewing', '待审核'), ('approved', '已确认'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='编辑状态')),
                ('generation_status', models.CharField(choices=[('not_started', '未开始'), ('pending', '等待中'), ('running', '生成中'), ('success', '成功'), ('failed', '失败')], default='not_started', max_length=20, verbose_name='生成状态')),
                ('user_prompt', models.TextField(blank=True, help_text='用户在生成章节时补充的自定义要求', verbose_name='用户补充提示词')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='outline.outline', verbose_name='大纲')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='outline.section', verbose_name='父章节')),
            ],
            options={
                'verbose_name': '大纲章节',
                'verbose_name_plural': '大纲章节',
                'db_table': 'outline_section',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_template_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='提示词模板ID')),
                ('prompt_version', models.CharField(blank=True, max_length=50, verbose_name='提示词版本号')),
                ('llm_model', models.CharField(blank=True, max_length=100, verbose_name='LLM模型')),
                ('input_summary', models.JSONField(default=dict, help_text="例：{'keywords': [...], 'kb_count': 5, 'requirement_count': 3}", verbose_name='输入摘要')),
                ('output_summary', models.JSONField(default=dict, help_text="例：{'word_count': 1500, 'has_tables': true}", verbose_name='输出摘要')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('async_task', models.ForeignKey(blank=True, help_text='单章节生成关联 section_generate，批量生成关联 outline_generate_batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.asynctask', verbose_name='异步任务')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('prompt_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generation.promptrun', verbose_name='AI运行记录')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_records', to='outline.section', verbose_name='章节')),
                ('workflow_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflownodeinstance', verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '章节生成记录',
                'verbose_name_plural': '章节生成记录',
                'db_table': 'outline_section_generation_record',
            },
        ),
        migrations.CreateModel(
            name='SectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='章节内容')),
                ('version_no', models.PositiveIntegerField(help_text='自增，每次生成或编辑递增', verbose_name='版本号')),
                ('source', models.CharField(choices=[('ai', 'AI生成'), ('manual', '手动编辑')], max_length=20, verbose_name='来源')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='outline.section', verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节版本',
                'verbose_name_plural': '章节版本',
                'db_table': 'outline_section_version',
            },
        ),
        migrations.AddIndex(
            model_name='outline',
            index=models.Index(fields=['project'], name='outline_project_c81767_idx'),
        ),
        migrations.AddIndex(
            model_name='outline',
            index=models.Index(fields=['lot'], name='outline_lot_id_1a4310_idx'),
        ),
        migrations.AddIndex(
            model_name='outline',
            index=models.Index(fields=['status'], name='outline_status_4031d8_idx'),
        ),
        migrations.AddIndex(
            model_name='outline',
            index=models.Index(fields=['is_current'], name='outline_is_curr_f66b81_idx'),
        ),
        migrations.AddConstraint(
            model_name='outline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('lot',), name='uniq_current_outline_per_lot'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['outline', 'parent', 'sort_order'], name='outline_sec_outline_67be0f_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['outline', 'level'], name='outline_sec_outline_361c13_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['generation_status'], name='outline_sec_generat_5b36a5_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['status'], name='outline_sec_status_9ca3ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('outline', 'parent', 'sort_order'), name='uniq_section_order_under_parent'),
        ),
        migrations.AddIndex(
            model_name='sectiongenerationrecord',
            index=models.Index(fields=['section', 'status'], name='outline_sec_section_bd8793_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiongenerationrecord',
            index=models.Index(fields=['async_task'], name='outline_sec_async_t_765e88_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiongenerationrecord',
            index=models.Index(fields=['prompt_run'], name='outline_sec_prompt__71c136_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionversion',
            index=models.Index(fields=['section', 'version_no'], name='outline_sec_section_cc57bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionversion',
            constraint=models.UniqueConstraint(fields=('section', 'version_no'), name='uniq_section_version'),
        ),
    ]
