# Generated by Django 5.2.1 on 2026-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_generation_meta',
            field=models.JSONField(blank=True, default=dict, help_text='存储 used_analysis_point_ids, used_rag_material_ids, missing_info, risk_flags, quality_report', verbose_name='正文生成元数据'),
        ),
    ]
