# Generated by Django 5.2.1 on 2026-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_add_content_generation_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionWritingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_key', models.CharField(db_index=True, help_text='如：project_management_plan, team_intro, evaluation_index_table', max_length=100, unique=True, verbose_name='模板键')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('applicable_section_roles', models.JSONField(blank=True, default=list, help_text="如：['technical_solution', 'service_plan']", verbose_name='适用章节定位')),
                ('applicable_keywords', models.JSONField(blank=True, default=list, help_text="如：['项目管理', '实施管理', '进度管理']", verbose_name='适用关键词')),
                ('expression_form', models.CharField(blank=True, default='body_text', help_text='body_text, table, commitment_letter, resume_table, mixed', max_length=50, verbose_name='表达形式')),
                ('writing_depth', models.CharField(blank=True, default='moderate', help_text='overview, moderate, detailed', max_length=50, verbose_name='写作深度')),
                ('template_content', models.TextField(help_text='包含 {{ slot_name }} 占位符的模板文本', verbose_name='模板内容')),
                ('required_slots', models.JSONField(blank=True, default=list, help_text='[{"name": "project_organization", "description": "项目组织架构", "allowed_rag_channels": ["company_info", "personnel"]}]', verbose_name='必填槽位')),
                ('optional_slots', models.JSONField(blank=True, default=list, help_text='非必填的内容槽位', verbose_name='可选槽位')),
                ('table_schemas', models.JSONField(blank=True, default=list, help_text='[{"name": "index_table", "columns": ["评审项", "招标要求", "响应章节"]}]', verbose_name='表格定义')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.PositiveIntegerField(default=50, help_text='数值越大优先级越高', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '章节撰写模板',
                'verbose_name_plural': '章节撰写模板',
                'db_table': 'outline_section_writing_template',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
