# Generated by Django 5.2.1 on 2026-06-04 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_add_section_writing_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('matrix_generation', '矩阵生成'), ('section_batch_generation', '章节批量生成')], db_index=True, max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('partial_success', '部分成功'), ('cancel_requested', '请求取消'), ('cancelled', '已取消'), ('paused', '已暂停')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('current_section_id', models.IntegerField(blank=True, null=True, verbose_name='当前处理章节ID')),
                ('current_section_title', models.CharField(blank=True, default='', max_length=500, verbose_name='当前处理章节标题')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery 任务ID')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('params', models.JSONField(blank=True, default=dict, help_text='存储 section_ids、force_overwrite、parallel、skip_on_failure 等参数', verbose_name='任务参数')),
                ('result', models.JSONField(blank=True, default=dict, help_text='存储失败明细、警告信息等结果数据', verbose_name='任务结果')),
            ],
            options={
                'verbose_name': '生成任务',
                'verbose_name_plural': '生成任务',
                'db_table': 'outline_generation_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='content_generated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='正文生成时间'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_generation_error',
            field=models.TextField(blank=True, default='', verbose_name='正文生成失败原因'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_generation_status',
            field=models.CharField(choices=[('pending', '待生成'), ('running', '生成中'), ('success', '已完成'), ('failed', '生成失败'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20, verbose_name='正文生成状态'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_matrix',
            field=models.JSONField(blank=True, default=dict, help_text='定义章节的写作边界和生成策略', verbose_name='内容责任矩阵'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_matrix_error',
            field=models.TextField(blank=True, default='', verbose_name='矩阵生成失败原因'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_matrix_status',
            field=models.CharField(choices=[('pending', '待生成'), ('generating', '生成中'), ('generated', '已生成'), ('edited', '已编辑'), ('failed', '生成失败')], db_index=True, default='pending', max_length=20, verbose_name='矩阵状态'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_matrix_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='矩阵更新时间'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_matrix_version',
            field=models.PositiveIntegerField(default=1, verbose_name='矩阵版本号'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_summary',
            field=models.TextField(blank=True, default='', verbose_name='章节摘要'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='正文字数'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['content_matrix_status'], name='outline_sec_content_de8299_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['content_generation_status'], name='outline_sec_content_5ad3fd_idx'),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='outline.outline', verbose_name='关联大纲'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['outline', 'status'], name='outline_gen_outline_a7429c_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['task_type'], name='outline_gen_task_ty_20683f_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['celery_task_id'], name='outline_gen_celery__6105a3_idx'),
        ),
    ]
