# Generated by Django 5.2.1 on 2026-06-08 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_add_object_key_to_bid_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchGenerationTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_index', models.PositiveIntegerField(help_text='任务创建时冻结的生成顺序', verbose_name='排序序号')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('running', '生成中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='记录重试生成的次数', verbose_name='重试次数')),
                ('generation_meta', models.JSONField(blank=True, default=dict, help_text='存储生成过程中的上下文元数据', verbose_name='生成元数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
            ],
            options={
                'verbose_name': '批量任务子项',
                'verbose_name_plural': '批量任务子项',
                'db_table': 'outline_batch_task_item',
                'ordering': ['sort_index'],
            },
        ),
        migrations.RenameIndex(
            model_name='biddocument',
            new_name='outline_bid_outline_0b94a9_idx',
            old_name='outline_bid_doc_outline_idx',
        ),
        migrations.AddField(
            model_name='generationtask',
            name='paused_at_index',
            field=models.PositiveIntegerField(default=0, help_text='暂停时的章节索引（仅用于展示，恢复基于子项状态）', verbose_name='暂停位置'),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('pause_requested', '请求暂停'), ('paused', '已暂停'), ('cancel_requested', '请求取消'), ('cancelled', '已取消'), ('completed', '已完成'), ('failed', '失败'), ('partial_success', '部分成功')], db_index=True, default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AddIndex(
            model_name='biddocument',
            index=models.Index(fields=['file_key'], name='outline_bid_file_ke_fd53e7_idx'),
        ),
        migrations.AddIndex(
            model_name='biddocument',
            index=models.Index(fields=['status'], name='outline_bid_status_045f18_idx'),
        ),
        migrations.AddField(
            model_name='batchgenerationtaskitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_task_items', to='outline.section', verbose_name='关联章节'),
        ),
        migrations.AddField(
            model_name='batchgenerationtaskitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outline.generationtask', verbose_name='关联任务'),
        ),
        migrations.AddIndex(
            model_name='batchgenerationtaskitem',
            index=models.Index(fields=['task', 'status'], name='outline_bat_task_id_ddb921_idx'),
        ),
        migrations.AddIndex(
            model_name='batchgenerationtaskitem',
            index=models.Index(fields=['section'], name='outline_bat_section_32d40a_idx'),
        ),
    ]
