# Generated by Django 5.2.1 on 2026-06-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_add_batch_task_item_and_paused_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='source',
            field=models.CharField(choices=[('manual', '手动创建'), ('preset', '系统预设'), ('ai', 'AI解析')], max_length=20, verbose_name='来源'),
        ),
    ]
