# Generated by Django 5.2.1 on 2026-06-27 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_rag_channel_and_trace_fields'),
        ('outline', '0008_add_manual_source_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outline_kb_bindings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_bindings', to='knowledge.knowledgebase', verbose_name='知识库')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_bindings', to='outline.outline', verbose_name='所属大纲')),
            ],
            options={
                'verbose_name': '大纲知识库关联',
                'verbose_name_plural': '大纲知识库关联',
                'db_table': 'outline_knowledge_base',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['outline', 'is_active'], name='outline_kno_outline_ae2a21_idx'), models.Index(fields=['outline', 'sort_order'], name='outline_kno_outline_c1bbaa_idx'), models.Index(fields=['knowledge_base'], name='outline_kno_knowled_8d43fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('outline', 'knowledge_base'), name='uniq_outline_kb')],
            },
        ),
    ]
