# Generated by Django 5.2.1 on 2026-06-27 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0009_create_outline_knowledge_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiongenerationrecord',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict, help_text='完整检索 trace: retrieval_plan/query/filters/warnings/latency_ms/used_mode', verbose_name='生成元数据'),
        ),
        migrations.AddField(
            model_name='sectiongenerationrecord',
            name='rag_sources',
            field=models.JSONField(blank=True, default=list, help_text='前端展示用，仅含 chunk_id/document_title/kb_name/channel/score/rank/page', verbose_name='RAG引用来源'),
        ),
        migrations.AddField(
            model_name='sectionversion',
            name='generated_from_record_id',
            field=models.IntegerField(blank=True, help_text='本次版本对应的 SectionGenerationRecord ID，用于关联 rag_sources', null=True, verbose_name='生成记录ID'),
        ),
        migrations.CreateModel(
            name='SectionManualSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_id', models.IntegerField(verbose_name='chunk ID')),
                ('document_id', models.IntegerField(verbose_name='文档 ID')),
                ('document_title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('kb_id', models.IntegerField(verbose_name='知识库 ID')),
                ('kb_name', models.CharField(max_length=255, verbose_name='知识库名称')),
                ('channel', models.CharField(max_length=32, verbose_name='RAG通道')),
                ('content_preview', models.TextField(blank=True, default='', verbose_name='内容预览')),
                ('section_path', models.CharField(blank=True, default='', max_length=255, verbose_name='文档内路径')),
                ('page_start', models.IntegerField(blank=True, null=True, verbose_name='起始页')),
                ('page_end', models.IntegerField(blank=True, null=True, verbose_name='结束页')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_sources', to='outline.section', verbose_name='所属章节')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_manual_sources', to=settings.AUTH_USER_MODEL, verbose_name='选择人')),
            ],
            options={
                'verbose_name': '章节手动选源',
                'verbose_name_plural': '章节手动选源',
                'db_table': 'section_manual_source',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['section'], name='section_man_section_8b73e7_idx'), models.Index(fields=['section', 'channel'], name='section_man_section_fe5171_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'chunk_id'), name='uniq_section_chunk')],
            },
        ),
    ]
