# Generated by Django 5.2.1 on 2026-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0015_section_mermaid_image_fields'),
        ('tender', '0007_alter_tenderfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='source_tender_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tender.tenderfile', verbose_name='源招标文件'),
        ),
    ]
