# Generated by Django 5.2.1 on 2026-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0016_alter_outline_source_tender_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalfactgroup',
            new_name='outline_glo_outline_e94224_idx',
            old_name='idx_global_fact_outline',
        ),
        migrations.RenameIndex(
            model_name='globalfactgroup',
            new_name='outline_glo_outline_26acb7_idx',
            old_name='idx_global_fact_order',
        ),
        migrations.AlterField(
            model_name='outline',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('generating', '生成中'), ('active', '活跃'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
