# Generated by Django 5.2.1 on 2026-08-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0017_rename_idx_global_fact_outline_outline_glo_outline_e94224_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='force_stopped',
            field=models.BooleanField(default=False, verbose_name='已被强制结束'),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='force_stopped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='强制结束时间'),
        ),
    ]
