# Generated by Django 5.2.1 on 2026-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0018_generationtask_force_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
