# Generated by Django 5.2.1 on 2026-08-11 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_rename_package_usage_key_idx_enterprise__package_7f0d5c_idx_and_more'),
        ('outline', '0019_generationtask_started_at'),
        ('projects', '0005_migrate_project_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidWordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('code', models.CharField(help_text='唯一标识，用于程序引用', max_length=100, unique=True, verbose_name='模板编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板说明')),
                ('scope_type', models.CharField(choices=[('system', '系统模板'), ('enterprise', '企业模板'), ('project', '项目模板')], db_index=True, default='system', max_length=20, verbose_name='作用域')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已发布'), ('disabled', '已停用'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('draft_object_key', models.CharField(blank=True, default='', max_length=500, verbose_name='草稿 MinIO 对象键')),
                ('draft_revision', models.PositiveIntegerField(default=0, help_text='ONLYOFFICE 每次保存（status=2）后 +1，不产生业务版本', verbose_name='草稿修订号')),
                ('draft_file_key', models.CharField(blank=True, db_index=True, default='', help_text='每次保存后更新，用于 ONLYOFFICE 缓存刷新', max_length=128, verbose_name='草稿 ONLYOFFICE 文件 Key')),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='草稿最后保存时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bid_word_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_word_templates', to='enterprise.companyprofile', verbose_name='所属企业')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_word_templates', to='projects.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bid_word_templates', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'Word 标书模板',
                'verbose_name_plural': 'Word 标书模板',
                'db_table': 'outline_bid_word_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BidWordTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('object_key', models.CharField(max_length=500, verbose_name='版本文件 MinIO 对象键')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('file_hash', models.CharField(db_index=True, help_text='用于编译缓存与生成快照追溯', max_length=64, verbose_name='文件 SHA256')),
                ('style_mapping', models.JSONField(blank=True, default=dict, help_text="逻辑样式名 → 模板实际样式名，如 {'heading1': '标题 1'}", verbose_name='样式映射')),
                ('variable_schema', models.JSONField(blank=True, default=list, help_text='模板中扫描到的变量 key 列表', verbose_name='变量清单')),
                ('validation_status', models.CharField(choices=[('not_validated', '未校验'), ('validating', '校验中'), ('passed', '校验通过'), ('failed', '校验失败')], default='not_validated', max_length=20, verbose_name='校验状态')),
                ('validation_result', models.JSONField(blank=True, default=dict, verbose_name='校验结果')),
                ('compile_status', models.CharField(blank=True, default='', help_text='compiled/failed，Phase 2 编译器接入后使用', max_length=20, verbose_name='编译状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='outline.bidwordtemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': 'Word 模板版本',
                'verbose_name_plural': 'Word 模板版本',
                'db_table': 'outline_bid_word_template_version',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddField(
            model_name='bidwordtemplate',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outline.bidwordtemplateversion', verbose_name='当前发布版本'),
        ),
        migrations.AddConstraint(
            model_name='bidwordtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_no'), name='uniq_template_version_no'),
        ),
        migrations.AddIndex(
            model_name='bidwordtemplate',
            index=models.Index(fields=['scope_type', 'status'], name='outline_bid_scope_t_c5e429_idx'),
        ),
        migrations.AddIndex(
            model_name='bidwordtemplate',
            index=models.Index(fields=['status'], name='outline_bid_status_0c3cf4_idx'),
        ),
    ]
