# Generated by Django 5.2.1 on 2026-08-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0020_bidwordtemplate_bidwordtemplateversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddocument',
            name='render_context_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='渲染时的变量取值快照（仅文本变量，不含图片）', verbose_name='渲染上下文快照'),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_documents', to='outline.bidwordtemplate', verbose_name='使用的模板'),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='template_file_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='模板文件 SHA256'),
        ),
        migrations.AddField(
            model_name='biddocument',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_documents', to='outline.bidwordtemplateversion', verbose_name='使用的模板版本'),
        ),
    ]
