# Generated by Django 5.2.1 on 2026-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0021_biddocument_render_context_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidwordtemplate',
            name='style_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="逻辑样式名 → 模板实际样式名，如 {'heading1': '标题 1'}", verbose_name='样式映射'),
        ),
        migrations.AddField(
            model_name='bidwordtemplateversion',
            name='preview_image_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='首页预览图 MinIO 对象键'),
        ),
        migrations.AddField(
            model_name='bidwordtemplateversion',
            name='preview_pdf_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='预览 PDF MinIO 对象键'),
        ),
    ]
